name: Cypress tests

on:
  push:
    branches:
      - "develop"

jobs:
  Cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cypress runs
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: cd client && npm install
      - name: create env file
        run: 
          touch .env
          echo DB_URL=${{ secrets.DB_URL }} >> .env
      - run: npm run build
      - run: npm start
      - run: npm test

  # Analyze:
  #   name: SonarCloud scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
